import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/Components/Nav";
import NameOfSite from "@/Components/NameOfSite";
import MainCard from "@/Components/MainCard";
import FavouriteCard from "@/Components/FavouriteCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <NameOfSite />
        {/* <MainCard /> */}
        <FavouriteCard />
        {children}
       
        </body>
    </html>
  );
}
